# Form implementation generated from reading ui file 'select_quiz.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, Qt, QSize
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QLabel, QFrame, QComboBox, QSizePolicy, QPushButton


class QuizSelect(QWidget):
    def __init__(self):
        super().__init__()

        # Attributes for this widget
        self.setObjectName("quizSelect")
        self.resize(792, 382)

        # Central Widget Attributes
        self.quizSelect_centralwidget = QWidget(self)
        self.quizSelect_centralwidget.setGeometry(QRect(150, 60, 511, 171))
        self.quizSelect_centralwidget.setObjectName("quizSelect_centralwidget")

        # Main Vertical Layout Attributes
        self.verticalLayout_2 = QVBoxLayout(self.quizSelect_centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        """
        Horizontal Layout Attributes
            Question Label
        """
        self.questionLabel_horizontalLayout = QtWidgets.QHBoxLayout()
        self.questionLabel_horizontalLayout.setObjectName("questionLabel_horizontalLayout")

        # Question Label Attributes - Child of above horizontal layout
        font = QtGui.QFont()
        font.setPointSize(24)
        self.question_label = QLabel(self.quizSelect_centralwidget)
        self.question_label.setFont(font)
        self.question_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.question_label.setObjectName("question_label")

        # Add question label to horizontal layout
        self.questionLabel_horizontalLayout.addWidget(self.question_label)

        # Add question label horizontal layout to main vertical layout
        self.verticalLayout_2.addLayout(self.questionLabel_horizontalLayout)

        """
        Horizontal Layout Attributes
            Choices ComboBox
        """
        self.combobox_horizontalLayout = QtWidgets.QHBoxLayout()
        self.combobox_horizontalLayout.setObjectName("combobox_horizontalLayout")

        # ComboBox Attributes
        font = QtGui.QFont()
        font.setPointSize(12)
        choice_size_policy = QSizePolicy(
            QSizePolicy.Policy.Fixed,
            QSizePolicy.Policy.Fixed
        )

        self.choice_comboBox = QComboBox(self.quizSelect_centralwidget)
        choice_size_policy.setHeightForWidth(
            self.choice_comboBox.sizePolicy().hasHeightForWidth()
        )
        self.choice_comboBox.setSizePolicy(choice_size_policy)
        self.choice_comboBox.setMinimumSize(QSize(300, 35))
        self.choice_comboBox.setFont(font)
        self.choice_comboBox.setObjectName("comboBox")

        # Add combobox to horizontal layout and then add the horizontal layout
        # to the main vertical layout
        self.combobox_horizontalLayout.addWidget(self.choice_comboBox)
        self.verticalLayout_2.addLayout(self.combobox_horizontalLayout)

        """
        Horizontal Layout Attributes
            PushButton
            PushButton
        """
        self.prev_next_pushButton_hlayout = QtWidgets.QHBoxLayout()
        self.prev_next_pushButton_hlayout.setObjectName("prev_next_pushButton_hlayout")
        self.start_pushButton = QPushButton(self.quizSelect_centralwidget)
        start_sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Fixed
        )

        # Set up the START button
        start_sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(start_sizePolicy)
        self.start_pushButton.setMinimumSize(QSize(110, 25))
        self.start_pushButton.setObjectName("start_pushButton")

        # Add the START button to the hlayout
        self.prev_next_pushButton_hlayout.addWidget(self.start_pushButton)

        # Set up the NEW QUIZ button
        self.new_quiz_pushButton = QtWidgets.QPushButton(self.quizSelect_centralwidget)
        new_quiz_sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Fixed,
            QSizePolicy.Policy.Fixed
        )
        new_quiz_sizePolicy.setHeightForWidth(self.new_quiz_pushButton.sizePolicy().hasHeightForWidth())
        self.new_quiz_pushButton.setSizePolicy(new_quiz_sizePolicy)
        self.new_quiz_pushButton.setMinimumSize(QSize(110, 25))
        self.new_quiz_pushButton.setObjectName("new_quiz_pushButton")

        # Add the NEW QUIZ button to the hlayout
        self.prev_next_pushButton_hlayout.addWidget(self.new_quiz_pushButton)

        # Add the hlayout to the main vertical layout
        self.verticalLayout_2.addLayout(self.prev_next_pushButton_hlayout)
